# Generated by Django 5.2.17 on 2026-09-14 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_saleline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBalance',
            fields=[
                ('sale', models.OneToOneField(db_column='sale_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='balance', serialize=False, to='core.sale')),
                ('client_id', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'v_sale_balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.client')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.payment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.sale')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_amount_positive')],
            },
        ),
    ]
